[versions]
kotlin-version = "2.2.21"
jackson-version = "2.20.1"
kotest-version = "5.9.1"
mockk-version = "1.14.6"
woodstox-core-version = "7.1.1"
picocli-version = "4.7.7"
logback-classic-version = "1.5.21"
swagger-annotations-version = "2.2.41"

# plugins
sonarqube-version = "7.1.0.6387"
spring-dependency-management-version = "1.1.7"
shadow-version = "8.3.8"
gradle-git-properties-version = "2.5.4"
devtools-ksp-version = "2.3.3"
micronaut-application-version = "4.6.1"
# to be removed
assertj-core-version = "3.27.6"

micronaut-platform-version = "4.10.2"
micronaut-serde-jackson-version = "2.16.2"

[libraries]
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson-version" }
jackson-jakarta-rs-xml-provider = { group = "com.fasterxml.jackson.jakarta.rs", name = "jackson-jakarta-rs-xml-provider", version.ref = "jackson-version" }
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson-version" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson-version" }

woodstox-core = { group = "com.fasterxml.woodstox", name = "woodstox-core", version.ref = "woodstox-core-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic-version" }
swagger-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swagger-annotations-version" }

micronaut-platform = { group = "io.micronaut.platform", name = "micronaut-parent", version.ref = "micronaut-platform-version" }
micronaut-serde-jackson = { group = "io.micronaut.serde", name = "micronaut-serde-jackson", version.ref = "micronaut-serde-jackson-version" }

# Tests
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest-version" }
kotest-assertions-json-jvm = { group = "io.kotest", name = "kotest-assertions-json-jvm", version.ref = "kotest-version" }
kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest-version" }
mockk-jvm = { group = "io.mockk", name = "mockk-jvm", version.ref = "mockk-version" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core-version" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management-version" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-version" }
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-git-properties-version" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp-version" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-application-version" }
